//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EPM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeTransfers
    {
        public int TransferID { get; set; }
        public Nullable<int> EmployeeID { get; set; }
        public string OriginalDepartment { get; set; }
        public string NewDepartment { get; set; }
        public Nullable<System.DateTime> TransferDate { get; set; }
        public string Notes { get; set; }
    
        public virtual Employees Employees { get; set; }
    }
}
