//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EPM.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EPMEntities : DbContext
    {
        public EPMEntities()
            : base("name=EPMEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Employees> Employees { get; set; }
        public virtual DbSet<EmployeeTrainings> EmployeeTrainings { get; set; }
        public virtual DbSet<EmployeeTransfers> EmployeeTransfers { get; set; }
        public virtual DbSet<Notifications> Notifications { get; set; }
        public virtual DbSet<Trainings> Trainings { get; set; }
    }
}
